language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'

# S: Build Lifecycle
install:
  - ./scripts/install.sh
before_script:
  - echo "start"
script:
  - npm run lint
  - npm run build
after_script:
  - echo "done"
# E: Build LifeCycle

after_success:
  - test $TRAVIS_PULL_REQUEST = "false" &&
    npx travis-deploy-once "npx semantic-release"
  - test $TRAVIS_PULL_REQUEST = "false" &&
    npx gh-pages -r https://"$GH_TOKEN"@github.com/clair-design/clair-design.github.io.git -b master -d .site
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
